-- MySQL Script generated by MySQL Workbench
-- Mon Jun 20 20:34:26 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema facturacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facturacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facturacion` DEFAULT CHARACTER SET utf8 ;
USE `facturacion` ;

-- -----------------------------------------------------
-- Table `facturacion`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturacion`.`usuarios` (
  `Codigo` VARCHAR(30) NOT NULL,
  `Nombre` VARCHAR(60) NOT NULL,
  `Email` VARCHAR(40) NULL,
  `Clave` VARCHAR(50) NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturacion`.`cliente` (
  `Identidad` VARCHAR(25) NOT NULL,
  `Nombre` VARCHAR(60) NULL,
  `Direccion` VARCHAR(120) NULL,
  `Email` VARCHAR(40) NULL,
  `Foto` BLOB NULL,
  PRIMARY KEY (`Identidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturacion`.`producto` (
  `Codigo` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(120) NOT NULL,
  `Existencia` INT NULL,
  `Precio` DECIMAL(8,2) NULL,
  `Imagen` BLOB NULL,
  PRIMARY KEY (`Codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturacion`.`factura` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdentidadCliente` VARCHAR(25) NULL,
  `Fecha` DATETIME NULL,
  `ISV` DECIMAL(8,2) NULL,
  `Descuento` DECIMAL(8,2) NULL,
  `SubTotal` DECIMAL(8,2) NULL,
  `Total` DECIMAL(8,2) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_factura_cliente_idx` (`IdentidadCliente` ASC) VISIBLE,
  CONSTRAINT `fk_factura_cliente`
    FOREIGN KEY (`IdentidadCliente`)
    REFERENCES `facturacion`.`cliente` (`Identidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `facturacion`.`detallefactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facturacion`.`detallefactura` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `IdFactura` INT NULL,
  `CodigoProducto` VARCHAR(50) NULL,
  `PrecioProducto` DECIMAL(8,2) NULL,
  `Cantidad` INT NULL,
  `Total` DECIMAL(8,2) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_detallefactura_factura_idx` (`IdFactura` ASC) VISIBLE,
  INDEX `fk_detallefactura_producto_idx` (`CodigoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_detallefactura_factura`
    FOREIGN KEY (`IdFactura`)
    REFERENCES `facturacion`.`factura` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detallefactura_producto`
    FOREIGN KEY (`CodigoProducto`)
    REFERENCES `facturacion`.`producto` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
